apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
        app.kubernetes.io/name: service-a
    spec:
      containers:
        - name: service-a
          image: andrea2000/servicea:1.0.0
          ports:
            - containerPort: 5000
